version: '3.8'
services:
  klock-database:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "9432:5432"
    volumes:
          - klock-database:/var/lib/postgresql/data

  klock-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './klock-frontend'
    volumes:
      - /app/node_modules
      - ./klock-frontend:/app
    ports:
      - '5173:5173'
    tty: true
 
  klock-backend:
    build: 
      dockerfile: Dockerfile
      context: './klock-backend'
    volumes:
      - ./klock-backend:/app
    ports:
      - '8000:8000'
    command: ["air", "-c", ".air.toml"]
    tty: true


volumes:  
  klock-database: